<?php
require_once __DIR__ . '/../config/bootstrap.php'; require_login();
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT); if (!$id) redirect('index.php');
$statement = $pdo->prepare('SELECT id, title, director, release_year, genre_id, description FROM movies WHERE id = ?'); $statement->execute([$id]); $movie = $statement->fetch(); if (!$movie) { flash('danger', 'Film tidak ditemukan.'); redirect('index.php'); }
$genres = $pdo->query('SELECT id, name FROM genres ORDER BY name')->fetchAll(); $errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $movie['title'] = clean_string($_POST['title'] ?? null); $movie['director'] = clean_string($_POST['director'] ?? null); $movie['release_year'] = filter_input(INPUT_POST, 'release_year', FILTER_VALIDATE_INT); $movie['genre_id'] = filter_input(INPUT_POST, 'genre_id', FILTER_VALIDATE_INT); $movie['description'] = clean_string($_POST['description'] ?? null); $currentYear = (int) date('Y');
    if ($movie['title'] === '' || strlen($movie['title']) > 200) $errors[] = 'Judul wajib diisi dan maksimal 200 karakter.'; if ($movie['director'] === '' || strlen($movie['director']) > 150) $errors[] = 'Sutradara wajib diisi dan maksimal 150 karakter.'; if (!$movie['release_year'] || $movie['release_year'] < 1888 || $movie['release_year'] > $currentYear) $errors[] = "Tahun rilis harus antara 1888 dan {$currentYear}."; if (!$movie['genre_id']) $errors[] = 'Genre wajib dipilih.';
    if (!$errors) { $check = $pdo->prepare('SELECT id FROM genres WHERE id = ?'); $check->execute([$movie['genre_id']]); if (!$check->fetch()) $errors[] = 'Genre tidak valid.'; }
    if (!$errors) { $update = $pdo->prepare('UPDATE movies SET title = ?, director = ?, release_year = ?, genre_id = ?, description = ? WHERE id = ?'); $update->execute([$movie['title'], $movie['director'], $movie['release_year'], $movie['genre_id'], $movie['description'] ?: null, $id]); flash('success', 'Film berhasil diubah.'); redirect('index.php'); }
}
$pageTitle = 'Edit Film'; require __DIR__ . '/../partials/header.php';
?>
<h1 class="h3 mb-3">Edit Film</h1><?php foreach ($errors as $error): ?><div class="alert alert-danger"><?= e($error) ?></div><?php endforeach; ?>
<form method="post" class="bg-white border rounded p-4"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row"><div class="col-md-8 mb-3"><label class="form-label" for="title">Judul</label><input class="form-control" id="title" name="title" value="<?= e($movie['title']) ?>" required maxlength="200"></div><div class="col-md-4 mb-3"><label class="form-label" for="release_year">Tahun rilis</label><input class="form-control" id="release_year" type="number" name="release_year" value="<?= e((string) $movie['release_year']) ?>" min="1888" max="<?= date('Y') ?>" required></div></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="director">Sutradara</label><input class="form-control" id="director" name="director" value="<?= e($movie['director']) ?>" required maxlength="150"></div><div class="col-md-6 mb-3"><label class="form-label" for="genre_id">Genre</label><select class="form-select" id="genre_id" name="genre_id" required><option value="">Pilih genre</option><?php foreach ($genres as $genre): ?><option value="<?= (int) $genre['id'] ?>" <?= (string) $movie['genre_id'] === (string) $genre['id'] ? 'selected' : '' ?>><?= e($genre['name']) ?></option><?php endforeach; ?></select></div></div><div class="mb-3"><label class="form-label" for="description">Deskripsi</label><textarea class="form-control" id="description" name="description" rows="4"><?= e($movie['description']) ?></textarea></div><button class="btn btn-primary">Simpan</button> <a class="btn btn-secondary" href="index.php">Batal</a></form>
<?php require __DIR__ . '/../partials/footer.php'; ?>
